version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: djangosecurity
    environment:
      - MYSQL_USER=security
      - MYSQL_DATABASE=security
      - MYSQL_PASSWORD=security
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./databases/mysql:/etc/mysql/conf.d
